<?php

namespace ClasseBundle\Repository;

/**
 * classsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classsRepository extends \Doctrine\ORM\EntityRepository
{
}
