<?php

namespace ClasseBundle\Repository;

/**
 * tccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tccRepository extends \Doctrine\ORM\EntityRepository
{



}
